version: '3.8'

services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"   
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env   

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
